name: 'Terraform Infrastructure Release'

on:
  # This section defines how the workflow is triggered. 
  # 'workflow_dispatch' allows manual running via the GitHub Actions tab.
  workflow_dispatch:
    inputs:
      aws_access_key_id:
        description: 'AWS_ACCESS_KEY_ID from AWS Academy Lab'
        required: true
        type: string
      aws_secret_access_key:
        description: 'AWS_SECRET_ACCESS_KEY from AWS Academy Lab'
        required: true
        type: string
      aws_session_token:
        description: 'AWS_SESSION_TOKEN (Security Token) from AWS Academy Lab'
        required: true
        type: string

env:
  # Environment variables accessible throughout the job
  WORKING_DIRECTORY: './iac'
  AWS_REGION: 'us-east-1' 

jobs:
  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest
    
    permissions:
      contents: read 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 'latest'

      # Uses the inputs defined above to configure the AWS environment
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ github.event.inputs.aws_access_key_id }}
          aws-secret-access-key: ${{ github.event.inputs.aws_secret_access_key }}
          aws-session-token: ${{ github.event.inputs.aws_session_token }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: ${{ env.WORKING_DIRECTORY }}
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.WORKING_DIRECTORY }}
